### ISSUE TITLE
Повышает характеристики питомца на 10%

### ISSUE THREAD

**Issue by Sin12ru** [orna-memory-hunting/storage#1178]
# Дружба и Неумение
### Плюсы
- **Повышает характеристики питомца на 10%**
- **Восполняет дополнительно 100% очков здоровья при использовании боевых умений или заклинаний, восстанавливающих здоровье через урон противнику**
- **Дарует 20% дополнительного урона при использовании стихийной уязвимости противника**
### Минусы
- _Снижает устойчивость к воде на 20%_
- _Снижает устойчивость к молнии на 15%_
- _Повышает урон от армии Балора на 30%._

**Comment by Voskreshatel** [comment]
Ошибка
