### ISSUE TITLE
Пошкодження стихії землі +5%

### ISSUE THREAD

**Issue by JopkaDobra** [orna-memory-hunting/storage#2111]
# Земля і кволість
### Плюсы
- **Пошкодження стихії землі +5%**
- **Підвищує шанс зустріти мобів для завдань **
### Минусы
- _Зменшує пошкодження пітьми на 20%_
- _Всі ваші характеристики будут зменшені на 40% під час захисту області_

**Comment by Nimfadorr** [comment]
Хз откуда это
