### ISSUE TITLE
You will receive 100% additional rewards when completing memories

### ISSUE THREAD

**Issue by Zufir** [orna-memory-hunting/storage#3182]
# Remembrance & Harm
### Плюсы
- **You will receive 100% additional rewards when completing memories**
- **Take 20% less damage from magical creatures.**
### Минусы
- _Damage from Raid ultimate attacks is increased by 20%_
- _You will take 75% additional self damage from status effects_

**Comment by Nimfadorr** [comment]
Осколок на 100% получения наград с мнемоглифов
