### ISSUE TITLE
Может прикрыть от входящего урона в размере 50% от максимального запаса очков здоровья и выше, шанс срабатывания 5%

### ISSUE THREAD

**Issue by Psaizek** [orna-memory-hunting/storage#942]
# Парапет и Погрешность
### Плюсы
- **Может прикрыть от входящего урона в размере 50% от максимального запаса очков здоровья и выше, шанс срабатывания 5%**
### Минусы
- _Снижает шанс критического удара на 20%_

**Comment by Voskreshatel** [comment]
Not available
